Complete javascript-carousel exercise
BenGrimmius/m2-1222-code-solutions pull request #6
Opened 2022-12-12 03:00 UTC by BenGrimmius

2022-12-13 03:40 UTC, TimelikeClosure requested changes
@BenGrimmius Please include a video with your pull request that demonstrates the carousel's functionality

2022-12-13 03:49 UTC, BenGrimmius commented
[Kapture 2022-12-12 at 19.48.06.gif.zip](https://github.com/BenGrimmius/m2-1222-code-solutions/files/10214090/Kapture.2022-12-12.at.19.48.06.gif.zip)

2022-12-13 05:14 UTC, TimelikeClosure requested changes

2022-12-13 05:14 UTC, TimelikeClosure commented on javascript-carousel/main.js
> +}
This is a _lot_ of code repetition. Please attempt to combine some of this in ways that let you re-use code between slides.

2022-12-16 03:16 UTC, BenGrimmius commented
![Kapture 2022-12-15 at 19 14 35](https://user-images.githubusercontent.com/103142603/208014001-f3903e9a-ceda-43d7-9636-04f1f0f04e62.gif)

2022-12-16 04:04 UTC, TimelikeClosure approved these changes

2022-12-16 04:04 UTC, merged